export const APPROVE_TEAM_SUCCESS = 'APPROVE_TEAM_SUCCESS';
export const APPROVE_TEAM_FAILED = 'APPROVE_TEAM_FAILED';
export const REJECT_TEAM_SUCCESS = 'REJECT_TEAM_SUCCESS';
export const REJECT_TEAM_FAILED = 'REJECT_TEAM_FAILED';