export const UPDATE_MATCH_RESULT_SUCCESS = 'UPDATE_MATCH_RESULT_SUCCESS';
export const UPDATE_MATCH_RESULT_FAILED = 'UPDATE_MATCH_RESULT_FAILED';
export const UPDATE_MATCH_INFO_SUCCESS = 'UPDATE_MATCH_INFO_SUCCESS';
export const UPDATE_MATCH_INFO_FAILED = 'UPDATE_MATCH_INFO_FAILED';